environment:

  TOX_ENV: "pywin"

  matrix:

    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: 3.7
      PYTHON_ARCH: 64
      TOX_ENV: "codecov"

    - PYTHON: "C:\\Python37"
      PYTHON_VERSION: 3.7
      PYTHON_ARCH: 32

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: 3.6
      PYTHON_ARCH: 64

    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: 3.6
      PYTHON_ARCH: 32

    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: 3.5
      PYTHON_ARCH: 64

    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: 3.5
      PYTHON_ARCH: 32

    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: 2.7
      PYTHON_ARCH: 64

    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: 2.7
      PYTHON_ARCH: 32

build: off

before_test:
  - "pip install tox"

test_script:
  - "tox -e %TOX_ENV%"