environment:

  matrix:

    - PYTHON: "C:\\Python39-x64"
      PYTHON_VERSION: 3.9
      PYTHON_ARCH: 64
      TOX_ENV: "py39"

    - PYTHON: "C:\\Python39"
      PYTHON_VERSION: 3.9
      PYTHON_ARCH: 32
      TOX_ENV: "py39"

    - PYTHON: "C:\\Python38-x64"
      PYTHON_VERSION: 3.8
      PYTHON_ARCH: 64
      TOX_ENV: "py38"

    - PYTHON: "C:\\Python38"
      PYTHON_VERSION: 3.8
      PYTHON_ARCH: 32
      TOX_ENV: "py38"

    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: 3.7
      PYTHON_ARCH: 64
      TOX_ENV: "py37"

    - PYTHON: "C:\\Python37"
      PYTHON_VERSION: 3.7
      PYTHON_ARCH: 32
      TOX_ENV: "py37"

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: 3.6
      PYTHON_ARCH: 64
      TOX_ENV: "py36"

    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: 3.6
      PYTHON_ARCH: 32
      TOX_ENV: "py36"

    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: 3.5
      PYTHON_ARCH: 64
      TOX_ENV: "py35"

    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: 3.5
      PYTHON_ARCH: 32
      TOX_ENV: "py35"

    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: 2.7
      PYTHON_ARCH: 64
      TOX_ENV: "py27"

    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: 2.7
      PYTHON_ARCH: 32
      TOX_ENV: "py27"

build: off

before_test:
  - "pip install tox"

test_script:
  - "tox -e %TOX_ENV%"