"""
hpterm-color terminal info

Generated: 2026-05-04T21:31:56.636866+00:00
Source: ncurses 6.4.20240113 (hash: c9aac1e1e58b)
"""

BOOL_CAPS = [
    'am',
    'ccc',
    'da',
    'db',
    'mir',
    'xhp',
    'xon',
]

NUM_CAPS = {
    'colors': 64,
    'cols': 80,
    'lh': 2,
    'lines': 24,
    'lm': 0,
    'lw': 8,
    'nlab': 8,
    'pairs': 8,
    'pb': 9600,
    'xmc': 0,
}

STR_CAPS = {
    'bel': b'\a',
    'bold': b'\x1b&dB',
    'cbt': b'\x1bi',
    'clear': b'\x1b&a0y0C\x1bJ',
    'cr': b'\r',
    'cub1': b'\b',
    'cud1': b'\x1bB',
    'cuf1': b'\x1bC',
    'cup': b'\x1b&a%p1%dy%p2%dC',
    'cuu1': b'\x1bA',
    'dch1': b'\x1bP',
    'dim': b'\x1b&dH',
    'dl1': b'\x1bM',
    'ed': b'\x1bJ$<1>',
    'el': b'\x1bK',
    'home': b'\x1b&a0y0C',
    'hpa': b'\x1b&a%p1%dC',
    'ht': b'\t',
    'hts': b'\x1b1',
    'il1': b'\x1bL',
    'ind': b'\n',
    'initp': b'\x1b&v%p2%da%p3%db%p4%dc%p5%dx%p6%dy%p7%dz%p1%dI',
    'kbs': b'\b',
    'kclr': b'\x1bJ',
    'kctab': b'\x1b2',
    'kcub1': b'\x1bD',
    'kcud1': b'\x1bB',
    'kcuf1': b'\x1bC',
    'kcuu1': b'\x1bA',
    'kdch1': b'\x1bP',
    'kdl1': b'\x1bM',
    'ked': b'\x1bJ',
    'kel': b'\x1bK',
    'kf1': b'\x1bp',
    'kf2': b'\x1bq',
    'kf3': b'\x1br',
    'kf4': b'\x1bs',
    'kf5': b'\x1bt',
    'kf6': b'\x1bu',
    'kf7': b'\x1bv',
    'kf8': b'\x1bw',
    'khome': b'\x1bh',
    'khts': b'\x1b1',
    'kich1': b'\x1bQ',
    'kil1': b'\x1bL',
    'kind': b'\x1bS',
    'kll': b'\x1bF',
    'knp': b'\x1bU',
    'kpp': b'\x1bV',
    'kri': b'\x1bT',
    'krmir': b'\x1bR',
    'ktbc': b'\x1b3',
    'meml': b'\x1bl',
    'memu': b'\x1bm',
    'op': b'\x1b&v0S',
    'pfkey': b'\x1b&f%p1%dk%p2%l%dL%p2%s',
    'pfloc': b'\x1b&f1a%p1%dk%p2%l%dL%p2%s',
    'pfx': b'\x1b&f2a%p1%dk%p2%l%dL%p2%s',
    'pln': b'\x1b&f%p1%dk%p2%l%dd0L%p2%s',
    'rev': b'\x1b&dB',
    'ri': b'\x1bT',
    'rmacs': b'\x0f',
    'rmir': b'\x1bR',
    'rmkx': b'\x1b&s0A',
    'rmln': b'\x1b&j@',
    'rmso': b'\x1b&d@',
    'rmul': b'\x1b&d@',
    'scp': b'\x1b&v%p1%dS',
    'sgr': b'\x1b&d%?%p7%t%\x27s\x27%c%;%p1%p3%|%p6%|%{2}%*%p2%{4}%*%+%p4%+%p5%{8}%*%+%\x27@\x27%+%c%?%p9%t%\x27\x0e\x27%c%e%\x27\x0f\x27%c%;',
    'sgr0': b'\x1b&d@\x0f',
    'smacs': b'\x0e',
    'smir': b'\x1bQ',
    'smkx': b'\x1b&s1A',
    'smln': b'\x1b&jB',
    'smso': b'\x1b&dJ',
    'smul': b'\x1b&dD',
    'tbc': b'\x1b3',
    'vpa': b'\x1b&a%p1%dY',
}
